### ISSUE TITLE
PGPMessage after encryption is always compressed

### ISSUE THREAD

**Issue by ivan-ushakov** [calccrypto/OpenPGP#18]
Fo some reason this code produce compressed message even if we don't want it:

```
// consider key loaded
PGPPublicKey publicKey;
const std::string data = "Hello!";
// set compression to 0
PGPMessage message = encrypt_pka(publicKey, data, "", 9, 0, false);

// at this step we have compressed packet with Tag8
std::string output = message.write();
```

To avoid this I have to do this:

```
// we have to switch off compression manually
message.set_comp(0);
std::string output = message.write();
```

Maybe it is by design, but then you need to add comment for `encrypt_pka()` function.

**Comment by calccrypto** [comment]
Can you show me an example? The compress argument `comp` does not refer to the PGPMessage compression. It is referring to the data being encrypted.

I tested with this code:

```cpp
#include "../OpenPGP.h"

int main(){
    std::ifstream file("public");
    PGPPublicKey pub(file);
    PGPMessage m = encrypt_pka(pub, "Hello", "", 9, 0, false);
    std::cout << m.write() << std::endl;
    // m.set_comp(0);
    std::cout << m.write() << std::endl;
    return 0;
}
```

Whether or not the `m.set_comp(0)` was there did not change anything. Additionally, I placed `std::cout`s around code in encrypt.cpp and PGPMessage.cpp where the variable `comp` showed up, and none of the data ever changed or went inside the `if (comp)` blocks.

I did find one thing that might be causing it: I didn't call the constructor at [encrypt.cpp line 179](https://github.com/calccrypto/OpenPGP/blob/master/encrypt.cpp#L179), which might have not set the compression algorithm in PGPMessage to `nullptr`. I changed this in the new commit. If this does not fix the problem for you, please tell me.

**Comment by ivan-ushakov** [comment]
Real code I use is very close to provided code. I think that problem was in default constructor and your commit fixed problem. Unfortunately I can't check you fix right now.

**Comment by calccrypto** [comment]
Should be fixed. Use the encrypt-pka and encrypt-sym commands in the executable.
