### ISSUE TITLE
Which platforms are supported?

### ISSUE THREAD

**Issue by GildedHonour** [calccrypto/OpenPGP#31]
Which platforms are supported?

**Comment by calccrypto** [comment]
OpenPGP should compile on any system that supports the C++11 standard. I do not believe anything used is platform specific.

**Comment by GildedHonour** [comment]
Allright
How can I generate a keypair from Key Material Packet?   https://tools.ietf.org/html/rfc4880#section-5.5

In js I can do it this way:

```

    var openpgp = require('openpgp');

    var privKey = getSomePrivKey();
    var options = {
        curve: 'secp256k1',
        userIds: {name: "my_user_id", email: "my@example.net"},
        passphrase: 'some passphrase',

       // this
        material: {
          key: privKey,
          subkey: privKey
        }
    };

    openpgp.generateKey(options).then(function(keypair) {
        var privkey = keypair.privateKeyArmored;
        var pubkey = keypair.publicKeyArmored;
        //..............


```

**Comment by calccrypto** [comment]
Please see [`exec/modules/generate_keypair.h`](https://github.com/calccrypto/OpenPGP/blob/master/exec/modules/generate_keypair.h#L139).

**Comment by GildedHonour** [comment]
1) Could you please show me how exactly that can be done? I see "subkey", but it has several members: pka, bits, sym.... Also, how can I proved what in my example "key"?

2) But ECC and secp256k1 aren't supported yet, right?

**Comment by calccrypto** [comment]
[`OpenPGP::KeyGen`](https://github.com/calccrypto/OpenPGP/blob/master/generatekey.h#L49) is analogous to the options structure. You need to provide a passphrase. Then, you fill it out with the [PKA](https://github.com/calccrypto/OpenPGP/blob/master/PKA/PKAs.h#L56), bitsize, [symmetric encryption algorithm](https://github.com/calccrypto/OpenPGP/blob/master/Encryptions/Encryptions.h#L70), and [hash algorithm](https://github.com/calccrypto/OpenPGP/blob/master/Hashes/Hashes.h#L64) you want. You also need to provide at least one User ID. You can then provide values for 0 or more subkeys. 

Once your `OpenPGP::Keygen` is filled to your liking, you can pass it into the `OpenPGP::generate_key` function to generate a Secret Key.

The Public Key can then be extracted from the Secret Key.

If you specifically want the primary key from the Secret Key, you can extract the first packet.
```
OpenPGP::SecretKey prikey = ...
OpenPGP::Packets packets = prikey.get_packets(); // or get_packets_clone()
OpenPGP::Tag5 key = std::static_pointer_cast <OpenPGP::Tag5> (prikey[0]);
```

Unfortunately, ECC has not been implemented yet. If you have to urge to implement ECC, I welcome it.

**Comment by GildedHonour** [comment]
Once your OpenPGP::Keygen is filled to your liking, you can pass it into the OpenPGP::generate_key function to generate a Secret Key.

yes, but in my example a private material key is pre-generated by a third-party and thus passed to "generate_key(...)" as an argument(s).

and "generate_key(...)" in turn generates a new private/public key

**Comment by calccrypto** [comment]
I am afraid that that kind of operation is not normally expected (that I know of), and thus not implemented. You could always take apart [`OpenPGP::generate_key`](https://github.com/calccrypto/OpenPGP/blob/master/generatekey.cpp#L80) and use the code within it to generate the proper signatures.
