### ISSUE TITLE
Mac error

### ISSUE THREAD

**Issue by slforense** [calccrypto/OpenPGP#37]
This project is not compiling for mac. 

Tag2.cpp:365:39: warning: suggest braces around initialization of subobject [-Wmissing-braces]
    std::array <uint32_t, 3> times = {0, 0, 0};
                                      ^~~~~~~
                                      {      }
1 warning generated.

Sub32.cpp:53:45: warning: all paths through this function will call itself [-Winfinite-recursion]
Sub32 & Sub32::operator=(const Sub32 & copy){
                                            ^
1 warning generated.
Subpacket.cpp:7:36: warning: all paths through this function will call itself [-Winfinite-recursion]
std::string Sub::show_title() const{
                                   ^
1 warning generated.
ar: creating archive libOpenPGP.a
/Volumes/2ndDisk/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libOpenPGP.a(Sub33.o) has no symbols

Sub33.o has 200B

-rw-r--r--  1 user  staff   200B Mar 21 03:07 Sub33.o

[make.txt](https://github.com/calccrypto/OpenPGP/files/1832202/make.txt)

**Comment by calccrypto** [comment]
There is no error. You are getting this message because you ran `make`, and not `make gpg-compatible`. `Sub33` can be found in GPG, but is not part of the standard, so the`Sub33` files are in `#ifdef` blocks, which is false when `GPG_COMPATIBLE` is not defined, resulting in an empty file being compiled.

**Comment by calccrypto** [comment]
Warning 1 is a [clang bug](https://bugs.llvm.org/show_bug.cgi?id=21629).
Warning 2 should be fixed by 66eaadecca981bb577b34443d347d433f5981b3f
I'm not sure why Warning 3 is still showing up. Are you compiling the latest copy?

**Comment by slforense** [comment]
Tks... sorry for taking so long to answer. Will test it and give a position.
