### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by soncemvo** [calccrypto/OpenPGP#39]
CMakeFiles/zm.dir/main.cpp.o: In function `__static_initialization_and_destruction_0(int, int)':
/home/soncemvo/zm/OpenPGP/Packets/../Subpackets/Tag2/../../Encryptions/Camellia_Const.h:33: undefined reference to `unhexlify(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/home/soncemvo/zm/OpenPGP/Packets/../Subpackets/Tag2/../../Encryptions/Camellia_Const.h:33: undefined reference to `unhexlify(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/home/soncemvo/zm/OpenPGP/Packets/../Subpackets/Tag2/../../Encryptions/Camellia_Const.h:33: undefined reference to `unhexlify(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/home/soncemvo/zm/OpenPGP/Packets/../Subpackets/Tag2/../../Encryptions/Camellia_Const.h:33: undefined reference to `unhexlify(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/home/soncemvo/zm/OpenPGP/Packets/../Subpackets/Tag2/../../Encryptions/Camellia_Const.h:33: undefined reference to `unhexlify(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
CMakeFiles/zm.dir/main.cpp.o:/home/soncemvo/zm/OpenPGP/Packets/../Subpackets/Tag2/../../Encryptions/Camellia_Const.h:33: more undefined references to `unhexlify(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)' follow

**Comment by calccrypto** [comment]
You are not linking with `common/includes.o`
