### ISSUE TITLE
Link with Qt project?

### ISSUE THREAD

**Issue by MangoCats** [calccrypto/OpenPGP#40]
Hi,

First, thanks for making this project.  I can't believe that libgcrypt and gpgme don't expose this kind of thing through their APIs... Second, the project clones and builds super clean (in Ubuntu 16.04), looks great.

I'm building an application in Qt, linked to gpgme and libgcrypt, that sort of hit a wall when I wanted to export the "meat" of the public keys from the gpg keyring in a format like X9.62 or similar that could be later passed to libgcrypt to validate signatures... that's when I found your project.

The issue I'm having is: when I link libOpenPGP.a to my project, I start getting linker errors as soon as I add a Key object to my code:

/usr/bin/ld: /home/mango/MainCore/OpenPGP/libOpenPGP.a(pgpzlib.o): undefined reference to symbol 'inflateInit2_'
/usr/lib/x86_64-linux-gnu/libz.so: error adding symbols: DSO missing from command line

I've messed around, tried adding -lz and -ldl to the linker arguments at various places, tried making a -shared libOpenPGP.so, but this one is stubborn, it just refuses to see the symbols in libz.so, even though the linker error is calling out a symlink that points right at the  the /lib/x86_64-linux-gnu/libz.so.1.2.8 file.  I've also tried installing the lib64z1-dev package, still no help - though installing libbz2-dev was required to get it OpenPGP to compile.

I looked briefly at the idea of bringing the OpenPGP source into my project, but I'm building with .pro/.pri files, and they're not too easy (possible?) to work with things like multiple files named Key.cpp, or some of the inclusion orders implemented in the makefiles.

Do you have any prior experience with these kinds of issues?  The error messages center around zlib, and I think Qt also compiles in their own zlib, so that may be a source of trouble.

Thanks for any help or insight.

**Comment by calccrypto** [comment]
I have never encountered this problem before. Maybe adding a `-L` that points to the system zlib might help it not find Qt's version.

**Comment by MangoCats** [comment]
I've tried different -L values, and gotten it to point at different system libz.so links (they all go back to the same file), I haven't managed to get it to point at /usr/lib/x86_64-linux-gnu/libz.a yet, though I did try some things with -Wl, -Bstatic, etc. (like this: https://stackoverflow.com/questions/3698321/g-linker-force-static-linking-if-static-library-exists) but no luck getting the desired effect with those yet.

As far as I can see from the g++ command and /usr/bin/ld error message, it _should_ be linking to the system libz.so files, which at their version of 1.2.8 _should_ have inflateInit2() defined, but it still gives those errors.

g++ -Wl,-O1 -Wl,-rpath,/home/mango/Qt/5.9/gcc_64/lib -o newApp cryptoForm.o mainwindow.o  blah blah blah  moc_mainwindow.o   -lOpenPGP -L/home/mango/app/OpenPGP -lgcrypt -lgpgme -lgpg-error -L/home/me/Qt/5.9/gcc_64/lib -lQt5Widgets -lQt5Gui -lQt5Network -lQt5Core -lGL -lpthread 

/usr/bin/ld: /home/mango/app/OpenPGP/libOpenPGP.a(pgpzlib.o): undefined reference to symbol 'inflateInit2_'

**Comment by MangoCats** [comment]
grep finds it:

grep inflateInit2_ /lib/x86_64-linux-gnu/libz.so.1.2.8 
Binary file /lib/x86_64-linux-gnu/libz.so.1.2.8 matches

is there a better dumping tool?

**Comment by calccrypto** [comment]
[`nm(1)`](https://linux.die.net/man/1/nm) and [`objdump(1)`](https://linux.die.net/man/1/objdump)

**Comment by MangoCats** [comment]
The thing that bugs me is that no matter which libz I direct the compiler to, it seems to be using another one - one that lacks inflateInit2_ ...  Rebuilding Qt from source takes time, but I might be trying that next and paying attention to their libz options.

**Comment by MangoCats** [comment]
It's in there: 
objdump -d /lib/x86_64-linux-gnu/libz.so.1.2.8 | grep inflateInit2
0000000000009ba0 <inflateInit2_@@Base>:
    9ba3:	0f 84 d7 00 00 00    	je     9c80 <inflateInit2_@@Base+0xe0>
    9bac:	0f 85 ce 00 00 00    	jne    9c80 <inflateInit2_@@Base+0xe0>
    9bb5:	0f 85 c5 00 00 00    	jne    9c80 <inflateInit2_@@Base+0xe0>
    9bc1:	0f 84 d0 00 00 00    	je     9c97 <inflateInit2_@@Base+0xf7>
    9bda:	0f 84 80 00 00 00    	je     9c60 <inflateInit2_@@Base+0xc0>
    9be9:	74 65                	je     9c50 <inflateInit2_@@Base+0xb0>
    9c03:	0f 84 87 00 00 00    	je     9c90 <inflateInit2_@@Base+0xf0>
    9c28:	75 06                	jne    9c30 <inflateInit2_@@Base+0x90>
    9c5b:	eb 8e                	jmp    9beb <inflateInit2_@@Base+0x4b>
    9c78:	e9 67 ff ff ff       	jmpq   9be4 <inflateInit2_@@Base+0x44>
    9c95:	eb 93                	jmp    9c2a <inflateInit2_@@Base+0x8a>
    9caa:	e9 f1 fe ff ff       	jmpq   9ba0 <inflateInit2_@@Base>
   1081b:	e8 80 93 ff ff       	callq  9ba0 <inflateInit2_@@Base>

**Comment by calccrypto** [comment]
What does `ldconfig -p | grep libz` say?

**Comment by MangoCats** [comment]
libzvbi.so.0 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libzvbi.so.0
	libzvbi.so (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libzvbi.so
	libzvbi-chains.so.0 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libzvbi-chains.so.0
	libzvbi-chains.so (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libzvbi-chains.so
	libzmq.so.5 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libzmq.so.5
	libzip.so.4 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libzip.so.4
	libzip.so (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libzip.so
	libzephyr.so.4 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libzephyr.so.4
	libzeitgeist-2.0.so.0 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libzeitgeist-2.0.so.0
	libzeitgeist-1.0.so.1 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libzeitgeist-1.0.so.1
	libzbar.so.0 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libzbar.so.0
	libz.so.1 (libc6,x86-64) => /lib/x86_64-linux-gnu/libz.so.1
	libz.so.1 (libc6) => /lib/i386-linux-gnu/libz.so.1
	libz.so.1 (libc6) => /usr/lib32/libz.so.1
	libz.so (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libz.so

Those last 4 are all links that resolve to: 

/lib/x86_64-linux-gnu/libz.so.1.2.8
/lib/i386-linux-gnu/libz.so.1.2.8
/usr/lib32/libz.so.1.2.8
/lib/x86_64-linux-gnu/libz.so.1.2.8

**Comment by mugwort-rc** [comment]
Hi,

It seems not linking libz.
Please add below config into your .pro file:

```
LIBS += -lOpenPGP -lgmp -lgmpxx -lbz2 -lz
```

**Comment by MangoCats** [comment]
O.K. - wow!  Hit the magic combo.  Thanks.

Last night I tried all combinations of including -lz, not including -lz, including -lz in different places...  With the Qt 5.9 downloaded from the Qt build servers, it would have just a few errors like the following when putting -lz in front of -lOpenPGP, and hundreds of errors when putting -lz behind -lOpenPGP.  Last night I built Qt 5.11 from source using the -system-zlib configure option, and with -lz in front it produced similar errors as before:

g++ -Wl,-O1 -Wl,-rpath,/opt/Qt5.11/lib -o app codeform.o mainwindow.o  blah blah blah moc_mainwindow.o   -lgmp -lgmpxx -lbz2 -lz -ldl -lOpenPGP -lgcrypt -lgpgme -lgpg-error -L/home/mango/app/OpenPGP -L/opt/Qt5.11/lib -lQt5Widgets -lQt5Gui -lQt5Network -lQt5Core -lGL -lpthread 
/usr/bin/ld: /home/mango/app/OpenPGP/libOpenPGP.a(pgpzlib.o): undefined reference to symbol 'inflateInit2_'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libz.so: error adding symbols: DSO missing from command line
Makefile:547: recipe for target 'app' failed

but... with -lz behind -lOpenPGP (still in front of the Qt libs), it now compiles and runs.

VICTORY!

Thanks for helping me through.

**Comment by MangoCats** [comment]
Hey,

Thanks for the libz linking issue.

More of a OpenPGP usage question this time:

I'm performing:

  gpgme_ctx_t   ctx;

  gpgme_error_t err;

  gpgme_data_t  keydata;


  initGpgme();

  gpgme_new( &ctx );

  gpgme_set_protocol( ctx, GPGME_PROTOCOL_OpenPGP );

  gpgme_set_armor( ctx, 1 );

    gpgme_data_new(&keydata);

  gpgme_op_keylist_start( ctx, NULL, 0 );

//...

  gpgme_op_export( ctx, "mykey", GPGME_EXPORT_MODE_MINIMAL, keydata );

  gpgme_data_seek( keydata, 0, SEEK_SET );

  gpgme_data_type_t dt = gpgme_data_identify(keydata,0);

  qDebug( "keydata type %d %s", dt, dt == GPGME_DATA_TYPE_PGP_KEY ?
"That's a PGP KEY" : "unexpected type" );

  char buf[8192];

  ssize_t sz = gpgme_data_read( keydata, buf, 8192 );

  qDebug( "Read %ld bytes", sz );

  QByteArray ba( buf, sz );

  qDebug( "%s", qPrintable( QString::fromUtf8( ba ) ) );

  qDebug( "Initializing ks" );

    OpenPGP::Key ks( ba.toStdString() );


and getting the result:


keydata type 19 That's a PGP KEY

Read 658 bytes

-----BEGIN PGP PUBLIC KEY BLOCK-----

Version: GnuPG v2


mFMEWxrk2hMJKyQDAwIIAQEHAgMEkGSoB7rnvIrDwS7h/90EETbFFgUBOG73NaAe

zxoq3yUuvFq2DDSjPAeqktQVkj4IOt6rw1EgZl1avjOQRJGnX7QD4pK2iH4EExMI

ACcFAlsa5NoCGwMFCQpMuAAFCwkIBwIGFQgJCgsCBBYCAwECHgECF4AACgkQla8L

V5oZr9nqVAD3VLg/mHCeKiwivzMFFSX5Rs66m8Ta97xVCmZtykstUAD/a4jtuFE+

5VAhE9Wp/nnG1kXpBcOuSKouKaO7lY4Ughu4VwRbGuTaEgkrJAMDAggBAQcCAwQz

aUNd3QfmV82aduJnc3k8cLN7f/eyJ/GwX0yjQLAcaiOLzj5/4tLz6tr6mPHHLpfC

tsU7k9DAPOwf/+ncStyIAwEIB4hnBBgTCAAPBQJbGuTaAhsMBQkKTLgAAAoJEJWv

C1eaGa/Zvw4A/RB4ebfk8k5HcJgyKVwwlJOItkgTR+vdLduoEYJnXR9CAP9bv2kB

emmdhVx4L2witrwOzDtqvDEZcN81Vr/2ydAxiA==

=2M5S

-----END PGP PUBLIC KEY BLOCK-----


Initializing ks

terminate called after throwing an instance of 'std::runtime_error'

  what():  Algorithm not found


Leaving me with the impression that I shouldn't be trying to
initialize an OpenPGP::Key object with this data...


If I want to get into the packet structure, what is the normal
approach? with OpenPGP?


Thanks,

**Comment by calccrypto** [comment]
I'm not sure what you mean by 
> and getting the result: (open the ..., comment formatting thinks the ASCII armor is a quotation)

I passed the key into OpenPGP and gpg, and both showed that it is a bad key:

```
$ ./OpenPGP list key
terminate called after throwing an instance of 'std::runtime_error'
  what():  Error: Input string length is not a multiple of 4.
Aborted (core dumped)
```
```
$ gpg --list-packets --verbose < key
gpg: invalid radix64 character 3A skipped
gpg: CRC error; 36F601 - D8CE52
gpg: [don't know]: invalid packet (ctb=55)
```

You are using OpenPGP correctly. The string `OpenPGP::Key` is expecting can be in binary blob or a ASCII armored base64 string.

Are you sure you are using gpgme correctly? Is `mykey` a good pattern for `gpgme_op_export`? Did you call `gpgme_op_export_start` somewhere in the `//...` to start the export?

As for the error you are getting: Can you modify [Key.cpp:124](https://github.com/calccrypto/OpenPGP/blob/master/Packets/Key.cpp#L124) to show the value? Does it match what you are expecting?

**Comment by calccrypto** [comment]
`If I want to get into the packet structure, what is the normal approach? with OpenPGP?`

1. Use the inherited `PGP::get_packets` function to get the list (a typecasted `std::vector`) of packets
2. For a given packet, you should use `Packet::get_tag` to get the type of packet. This number matches the number specified in [RFC 4880](https://github.com/calccrypto/OpenPGP/blob/master/Packets/Packet.h#L39) and will tell you how to typecast the packet from the generic `OpenPGP::Packet::Tag` type to a specific `OpenPGP::Packet::Tag<number>` type. 
3. Check the RFC and/or header to figure out what the packet contains and use the `get_*` and `set_*` functions to access and modify the data.

**Comment by MangoCats** [comment]
I mean: the output of that code follows, including the ASCII armored data
blob and the terminate message.

I tried binary blob format first (413 bytes, as delivered from
gpgme_op_export() ), but got the same result - and when I looked into the
Key constructors I only saw input for std::string, so that's why I switched
over to ASCII armored format.

>Are you sure you are using gpgme correctly?

Frankly, no.  I haven't gotten a completely intelligible result from
gpgme_op_export() yet, but some things do seem to track.  For instance:
"mykey" gets listed by gpg -k, and when I delete it from the keyring, then
gpgme_op_export() returns no data.  If I create multiple keys with the name
"mykey" then I get the expected multiple of data back from gpgme_op_export()
- 413 bytes for one key, 826 bytes for two, etc. These are ECDSA keys, if
that makes a difference? I am making OpenPGP with gpg-compatible. Also, for
the key info that gpgme does reveal:

 qDebug( "Examining subkey:" );

              qDebug( "           keyid: %s", subkey->keyid            );

              qDebug( "Can authenticate: %d", subkey->can_authenticate );

              qDebug( "     Can certify: %d", subkey->can_certify      );

              qDebug( "     Can encrypt: %d", subkey->can_encrypt      );

              qDebug( "        Can sign: %d", subkey->can_sign         );

              qDebug( "     Card number: %s", subkey->card_number      );

              qDebug( "           Curve: %s", subkey->curve            );

              qDebug( "        Disabled: %d", subkey->disabled         );

              qDebug( "         Expired: %d", subkey->expired          );

              qDebug( "         Expires: %ld",subkey->expires          );

              qDebug( "     fingerprint: %s", subkey->fpr              );

              qDebug( "         invalid: %d", subkey->invalid          );

              qDebug( "     is card key: %d", subkey->is_cardkey       );

              qDebug( "        is de vs: %d", subkey->is_de_vs         );

              qDebug( "    is qualified: %d", subkey->is_qualified     );

              qDebug( "         keygrip: %s", subkey->keygrip          );

              qDebug( "          length: %d", subkey->length           );

              qDebug( "         revoked: %d", subkey->revoked          );

              qDebug( "          secret: %d", subkey->secret           );

              qDebug( "       timestamp: %ld",subkey->timestamp        );


that all seems to track correctly.


My impression from here:
https://www.gnupg.org/documentation/manuals/gpgme/Exporting-Keys.html is
that gpgme_op_export() is a blocking call, whereas gpgme_op_export_start()
returns immediately so other processing can take place in parallel and then
gpgme_wait() will ensure the result is complete before proceeding, but
returns the same data as the blocking call... it's a pattern they seem to
use many places. Am I interpreting that wrong?

So, in a big HMMMMM moment, I've imported the gnupg suite of source code as
git modules in my project and built them to the recent tags (2.2.8 for gpg,
1.11.1 for gpgme, etc.), tried to get the app to link and run with those
builds that are installed in /usr/local, and didn't really succeed - the
gpgme context in my app still reports running /usr/bin/gpg2 with version
2.1.11, but... behavior has changed, and now I'm not getting an exception
when passing the blob to OpenPGP:Key ks( ba.toStdString() ); I did put a std
::cout << "size " << size << " version " << version << " time " << time << "
pka " << pka << "\n"; in Packets/Key.cpp:124, but that's not triggering
anymore. After I make ks, I: qDebug( "ks.keyid():%s", qPrintable( QString::
fromStdString( ks.keyid() ) ) ); and that shows: ks.keyid():�� W� ��  ,
still not thrilling, but not crashing, either...

I do think I want to go "full build control" on this, gpg changes too much
across versions and I'd much rather just pick a version and run with its
quirks, the whole library wrangling thing is just a mess, though.

**Comment by calccrypto** [comment]
I have no idea how to use gpgme (one of the reasons why I wrote OpenPGP), but I think you are interpreting the documentation correctly.

I do not recognize a lot of the values you printed with qDebug. The OpenPGP standard does not have a `card_number` field. I do not know if GPG calculates that or gets it from the key data directly. Could that be the reason why its failing? GPG might have added fields to the standard, causing OpenPGP to fail, since it doesn't know how to handle these fields.

Also, elliptic curves were not fully implemented in this library. I got some pull requests for reading, storing, and writing elliptic curve values, but that was it. I don't think there is any code to do computations with them.

**Comment by MangoCats** [comment]
I'm fine using gpgme for most things, keeping secret keys on the keyring,
signing, verifying, trust models, etc. but... I want to extract the public
keys and communicate them "bare" (like in X9.62 or similar format) to other
users, without all the OpenPGP wrappings, and use those public keys to
validate signatures.  That extraction of the bare public key is where gpgme
is failing me at the moment... they seem to be intentionally avoiding it.

This library wrangling of the various gpg versions is also a real mess.
When gpg builds from the git repo, it installs itself to /usr/local/bin
which puts it in-front of the /usr/bin in my path and screws up things like
apt-get because it fails when you run it, demanding a newer libgcrypt than
it finds in the default path, seems the /usr/local/lib path doesn't get
priority location like /usr/local/bin did.

**Comment by calccrypto** [comment]
Give [this](https://github.com/calccrypto/OpenPGP/commit/f78f8546369d4a7c10fd6fb88e03510532544246) a try.

**Comment by MangoCats** [comment]
Same result, binary or ASCII, for what it's worth, here's the binary blob
shown as hex:

keydata type 19 That's a PGP KEY

Read 412 bytes

9853045b1ae4da13092b24030302080101070203049064a807bae7bc8ac3c12ee1ffdd041136c5160501386ef735a01ecf1a2adf252ebc5ab60c34a33c07aa92d415923e083adeabc35120665d5abe33904491a75fb403e292b6887e04131308002705025b1ae4da021b0305090a4cb800050b09080702061508090a0b020416020301021e01021780000a091095af0b579a19afd9ea5400f754b83f98709e2a2c22bf33051525f946ceba9bc4daf7bc550a666dca4b2d5000ff6b88edb8513ee5502113d5a9fe79c6d645e905c3ae48aa2e29a3bb958e14821bb857045b1ae4da12092b24030302080101070203043369435ddd07e657cd9a76e26773793c70b37b7ff7b227f1b05f4ca340b01c6a238bce3e7fe2d2f3eadafa98f1c72e97c2b6c53b93d0c03cec1fffe9dc4adc8803010807886704181308000f05025b1ae4da021b0c05090a4cb800000a091095af0b579a19afd9bf0e00fd107879b7e4f24e47709832295c30949388b6481347ebdd2ddba81182675d1f4200ff5bbf69017a699d855c782f6c22b6bc0ecc3b6abc311970df3556bff6c9d03188


ks.keyid():�� W� ��


Also, for what it's worth, I think I found the PGP RFC 4880-5.5 key output
code in: gnupg/g10/build-packet.c:458 (tag 2.2.8) do_key( out, ctb,
PKT_public_key *pk );

**Comment by calccrypto** [comment]
The key id is messed up because it is in binary. You have to use `hexlify` to get it to print in hex.

We might not be doing the same thing. When I run

`std::cout << OpenPGP::Key(unhexlify("9853045b1ae4da13092b24030302080101070203049064a807bae7bc8ac3c12ee1ffdd041136c5160501386ef735a01ecf1a2adf252ebc5ab60c34a33c07aa92d415923e083adeabc35120665d5abe33904491a75fb403e292b6887e04131308002705025b1ae4da021b0305090a4cb800050b09080702061508090a0b020416020301021e01021780000a091095af0b579a19afd9ea5400f754b83f98709e2a2c22bf33051525f946ceba9bc4daf7bc550a666dca4b2d5000ff6b88edb8513ee5502113d5a9fe79c6d645e905c3ae48aa2e29a3bb958e14821bb857045b1ae4da12092b24030302080101070203043369435ddd07e657cd9a76e26773793c70b37b7ff7b227f1b05f4ca340b01c6a238bce3e7fe2d2f3eadafa98f1c72e97c2b6c53b93d0c03cec1fffe9dc4adc8803010807886704181308000f05025b1ae4da021b0c05090a4cb800000a091095af0b579a19afd9bf0e00fd107879b7e4f24e47709832295c30949388b6481347ebdd2ddba81182675d1f4200ff5bbf69017a699d855c782f6c22b6bc0ecc3b6abc311970df3556bff6c9d03188")).show() << std::endl;`

I get:

```
Old: Public-Key (Tag 6)
    Version: 4 - New
    Creation Time: Fri Jun 8 20:19:38 UTC 2018
    Public Key Algorithm: ECDSA (pka 19)
    ECDSA brainpoolP256r1
    ECDSA ec point: 049064a807bae7bc8ac3c12ee1ffdd041136c5160501386ef735a01ecf1a2adf252ebc5ab60c34a33c07aa92d415923e083adeabc35120665d5abe33904491a75f
Old: User ID (Tag 13)
    User ID: Ⓐ
Old: Signature (Tag 2)
    Version: 4
    Signature Type: Positive certification of a User ID and Public-Key packet (type 0x13)
    Public Key Algorithm: ECDSA (pka 19)
    Hash Algorithm: SHA256 (hash 8)
    Hashed Sub:
        Signature Creation Time Subpacket (sub 2) (4 octets)
            Creation Time: Fri Jun 8 20:19:38 UTC 2018
        Key Flags Subpacket (sub 27) (1 octets)
            Flag - This key may be used to certify other keys (key 0x01)
            Flag - This key may be used to sign data (key 0x02)
        Key Expiration Time Subpacket (sub 9) (4 octets)
            Key Expiration Time: Wed Nov 29 20:19:38 UTC 2023
        Preferred Symmetric Algorithms Subpacket (sub 11) (4 octets)
            sym alg - AES256 (sym 9)
            sym alg - AES192 (sym 8)
            sym alg - AES128 (sym 7)
            sym alg - TRIPLEDES (sym 2)
        Preferred Hash Algorithms Subpacket (sub 21) (5 octets)
            hash alg - SHA256 (hash 8)
            hash alg - SHA384 (hash 9)
            hash alg - SHA512 (hash 10)
            hash alg - SHA224 (hash 11)
            hash alg - SHA1 (hash 2)
        Preferred Compression Algorithms Subpacket (sub 22) (3 octets)
            comp alg - ZLIB {RFC1950} (comp 2)
            comp alg - BZip2 {BZ2} (comp 3)
            comp alg - ZIP {RFC1951} (comp 1)
        Features Subpacket (sub 30) (1 octets)
            Flag - Modification Detection (packets 18 and 19) (feat 1)
        Key Server Preferences Subpacket (sub 23) (1 octets)
            Flag - NO-MODIFY (key 0x80)
    Unhashed Sub:
        Issuer Subpacket (sub 16) (8 octets)
            Key ID: 95af0b579a19afd9
    Hash Left 16 Bits: ea54
    ECDSA r (247 bits): 54b83f98709e2a2c22bf33051525f946ceba9bc4daf7bc550a666dca4b2d50
    ECDSA s (255 bits): 6b88edb8513ee5502113d5a9fe79c6d645e905c3ae48aa2e29a3bb958e14821b
Old: Public-Subkey (Obsolete Comment Packet) (Tag 14)
    Version: 4 - New
    Creation Time: Fri Jun 8 20:19:38 UTC 2018
    Public Key Algorithm: ECDH (pka 18)
    ECDH brainpoolP256r1
    ECDH ec point: 043369435ddd07e657cd9a76e26773793c70b37b7ff7b227f1b05f4ca340b01c6a238bce3e7fe2d2f3eadafa98f1c72e97c2b6c53b93d0c03cec1fffe9dc4adc88
Old: Signature (Tag 2)
    Version: 4
    Signature Type: Subkey Binding Signature (type 0x18)
    Public Key Algorithm: ECDSA (pka 19)
    Hash Algorithm: SHA256 (hash 8)
    Hashed Sub:
        Signature Creation Time Subpacket (sub 2) (4 octets)
            Creation Time: Fri Jun 8 20:19:38 UTC 2018
        Key Flags Subpacket (sub 27) (1 octets)
            Flag - This key may be used to encrypt communications (key 0x04)
            Flag - This key may be used to encrypt storage (key 0x08)
        Key Expiration Time Subpacket (sub 9) (4 octets)
            Key Expiration Time: Wed Nov 29 20:19:38 UTC 2023
    Unhashed Sub:
        Issuer Subpacket (sub 16) (8 octets)
            Key ID: 95af0b579a19afd9
    Hash Left 16 Bits: bf0e
    ECDSA r (253 bits): 107879b7e4f24e47709832295c30949388b6481347ebdd2ddba81182675d1f42
    ECDSA s (255 bits): 5bbf69017a699d855c782f6c22b6bc0ecc3b6abc311970df3556bff6c9d03188
```

**Comment by MangoCats** [comment]
Very nice, that is indeed the key - correct creation time, brainpoolP256r1
curve and all... trying .show() now, and I get the same, thank you, this is
awesome!

Now, if I understand correctly, the ECDH ec point: data of the public key
is all that's really needed to verify the a signature with the private key
(assuming you know the algorithm, curve, etc...) the next big fun will be
reconstructing a key from just that data and using it.

Thanks again - good progress for the day for me.

Mike

keydata type 19 That's a PGP KEY

Read 412 bytes

9853045b1ae4da13092b24030302080101070203049064a807bae7bc8ac3c12ee1ffdd041136c5160501386ef735a01ecf1a2adf252ebc5ab60c34a33c07aa92d415923e083adeabc35120665d5abe33904491a75fb403e292b6887e04131308002705025b1ae4da021b0305090a4cb800050b09080702061508090a0b020416020301021e01021780000a091095af0b579a19afd9ea5400f754b83f98709e2a2c22bf33051525f946ceba9bc4daf7bc550a666dca4b2d5000ff6b88edb8513ee5502113d5a9fe79c6d645e905c3ae48aa2e29a3bb958e14821bb857045b1ae4da12092b24030302080101070203043369435ddd07e657cd9a76e26773793c70b37b7ff7b227f1b05f4ca340b01c6a238bce3e7fe2d2f3eadafa98f1c72e97c2b6c53b93d0c03cec1fffe9dc4adc8803010807886704181308000f05025b1ae4da021b0c05090a4cb800000a091095af0b579a19afd9bf0e00fd107879b7e4f24e47709832295c30949388b6481347ebdd2ddba81182675d1f4200ff5bbf69017a699d855c782f6c22b6bc0ecc3b6abc311970df3556bff6c9d03188



ks.show():Old: Public-Key (Tag 6) Version: 4 - New

Creation Time: Fri Jun 8 20:19:38 UTC 2018

Public Key Algorithm: ECDSA (pka 19)

ECDSA brainpoolP256r1

ECDSA ec point:
049064a807bae7bc8ac3c12ee1ffdd041136c5160501386ef735a01ecf1a2adf252ebc5ab60c34a33c07aa92d415923e083adeabc35120665d5abe33904491a75f

Old: User ID (Tag 13)

User ID: Ⓐ

Old: Signature (Tag 2)

Version: 4

Signature Type: Positive certification of a User ID and Public-Key packet
(type 0x13)

Public Key Algorithm: ECDSA (pka 19)

Hash Algorithm: SHA256 (hash 8)

Hashed Sub:

Signature Creation Time Subpacket (sub 2) (4 octets)

Creation Time: Fri Jun 8 20:19:38 UTC 2018

Key Flags Subpacket (sub 27) (1 octets)

Flag - This key may be used to certify other keys (key 0x01)

Flag - This key may be used to sign data (key 0x02)

Key Expiration Time Subpacket (sub 9) (4 octets)

Key Expiration Time: Wed Nov 29 20:19:38 UTC 2023

Preferred Symmetric Algorithms Subpacket (sub 11) (4 octets)

sym alg - AES256 (sym 9)

sym alg - AES192 (sym 8)

sym alg - AES128 (sym 7)

sym alg - TRIPLEDES (sym 2)

Preferred Hash Algorithms Subpacket (sub 21) (5 octets)

hash alg - SHA256 (hash 8)

hash alg - SHA384 (hash 9)

hash alg - SHA512 (hash 10)

hash alg - SHA224 (hash 11)

hash alg - SHA1 (hash 2)

Preferred Compression Algorithms Subpacket (sub 22) (3 octets)

comp alg - ZLIB {RFC1950} (comp 2)

comp alg - BZip2 {BZ2} (comp 3)

comp alg - ZIP {RFC1951} (comp 1)

Features Subpacket (sub 30) (1 octets)

Flag - Modification Detection (packets 18 and 19) (feat 1)

Key Server Preferences Subpacket (sub 23) (1 octets)

Flag - NO-MODIFY (key 0x80)

Unhashed Sub:

Issuer Subpacket (sub 16) (8 octets)

Key ID: 95af0b579a19afd9

Hash Left 16 Bits: ea54

ECDSA r (247 bits):
54b83f98709e2a2c22bf33051525f946ceba9bc4daf7bc550a666dca4b2d50

ECDSA s (255 bits):
6b88edb8513ee5502113d5a9fe79c6d645e905c3ae48aa2e29a3bb958e14821b

Old: Public-Subkey (Obsolete Comment Packet) (Tag 14)

Version: 4 - New

Creation Time: Fri Jun 8 20:19:38 UTC 2018

Public Key Algorithm: ECDH (pka 18)

ECDH brainpoolP256r1

ECDH ec point:
043369435ddd07e657cd9a76e26773793c70b37b7ff7b227f1b05f4ca340b01c6a238bce3e7fe2d2f3eadafa98f1c72e97c2b6c53b93d0c03cec1fffe9dc4adc88

Old: Signature (Tag 2)

Version: 4

Signature Type: Subkey Binding Signature (type 0x18)

Public Key Algorithm: ECDSA (pka 19)

Hash Algorithm: SHA256 (hash 8)

Hashed Sub:

Signature Creation Time Subpacket (sub 2) (4 octets)

Creation Time: Fri Jun 8 20:19:38 UTC 2018

Key Flags Subpacket (sub 27) (1 octets)

Flag - This key may be used to encrypt communications (key 0x04)

Flag - This key may be used to encrypt storage (key 0x08)

Key Expiration Time Subpacket (sub 9) (4 octets)

Key Expiration Time: Wed Nov 29 20:19:38 UTC 2023

Unhashed Sub:

Issuer Subpacket (sub 16) (8 octets)

Key ID: 95af0b579a19afd9

Hash Left 16 Bits: bf0e

ECDSA r (253 bits):
107879b7e4f24e47709832295c30949388b6481347ebdd2ddba81182675d1f42

ECDSA s (255 bits):
5bbf69017a699d855c782f6c22b6bc0ecc3b6abc311970df3556bff6c9d03188
