### ISSUE TITLE
Cannot decrypt GnuPG message with "partial continue" structure

### ISSUE THREAD

**Issue by kaie** [calccrypto/OpenPGP#43]
I'm trying to decrypt a message with the command line tool, using the decrypt-pka command. It fails inside Message::meaningful. In Message::match p->get_tag() returns 254.

The message was sent using GnuPG. I've built with gpg-debug to enable compatibility.

"OpenPGP show" reports:

Old: Public-Key Encrypted Session Key (Tag 1)
    Version: 3
    KeyID: ...
    Public Key Algorithm: RSA (Encrypt or Sign) (pka 1)
    RSA m**e mod n (3072 bits): ...
Old: Public-Key Encrypted Session Key (Tag 1)
    Version: 3
    KeyID: ...
    Public Key Algorithm: RSA (Encrypt or Sign) (pka 1)
    RSA m**e mod n (4090 bits): ...
New: Symmetrically (Conventional) Encrypted Data (Tag 9) (partial start)
    Encrypted Data (2048 octets): ...
Old:  (partial end)
    ...

"pgpdump" reports:

Old: Public-Key Encrypted Session Key Packet(tag 1)(396 bytes)
	New version(3)
	Key ID - ...
	Pub alg - RSA Encrypt or Sign(pub 1)
	RSA m^e mod n(3072 bits) - ...
		-> m = sym alg(1 byte) + checksum(2 bytes) + PKCS-1 block type 02
Old: Public-Key Encrypted Session Key Packet(tag 1)(524 bytes)
	New version(3)
	Key ID - ...
	Pub alg - RSA Encrypt or Sign(pub 1)
	RSA m^e mod n(4090 bits) - ...
		-> m = sym alg(1 byte) + checksum(2 bytes) + PKCS-1 block type 02
New: Symmetrically Encrypted Data Packet(tag 9)(2048 bytes) partial start
	Encrypted data [sym alg is specified in pub-key encrypted session key]
New: 	(1024 bytes) partial continue
New: 	(475 bytes) partial end

**Comment by calccrypto** [comment]
Can you please post the message, so that I can trace what it is doing in the code?

**Comment by calccrypto** [comment]
Please pull to c21916a18f65bd8bc0a4ffa6ad019d56cc1baf33 and give it a try

**Comment by kaie** [comment]
[encrypted.txt](https://github.com/calccrypto/OpenPGP/files/2880621/encrypted.txt)

This is the encrypted file, I hope it is helpful.

**Comment by calccrypto** [comment]
Please give the latest master another try.

**Comment by calccrypto** [comment]
@kaie Have the most recent updates fixed this?

**Comment by kaie** [comment]
Hello Jason, sorry for the delay. It's not yet working for me, maybe I'm doing something wrong. I get an error:

./cli/OpenPGP decrypt-pka testmail-0227.private passphrase enc.pgp 
terminate called after throwing an instance of 'std::runtime_error'
  what():  Error: Data does not form a meaningful PGP Key
Aborted (core dumped)

The key pair was generated using:
./cli/OpenPGP generate-keypair --phash SHA256 --pkeysize 3072 --psig SHA256 --shash SHA256 --skeysize 3072 --ssig SHA256 -e idonttellyou@kuix.de -u "Test Mail" -o testmail-0227 -p passphrase

The public key was copied to a different VM, imported into gpg, and a 5 K test message was sent encrypted-only from Thunderbird with Enigmail/GnuPG.

Build flags were
cmake -DCMAKE_INSTALL_PREFIX=/home/user/local/openpgp -DGPG_COMPATIBLE=True ..

I built revision 80e5790ce04ebd00ca38cffc99a843e897e314b1 from Feb 25.

**Comment by kaie** [comment]
File enc.pgp contains just the
-----BEGIN PGP MESSAGE-----
...
-----END PGP MESSAGE-----
part of the email message.

File testmail-0227.private contains the unmodified private key as generated by the above key generation command.

**Comment by kaie** [comment]
Jason, if you point me to your private key, I can send you an equivalent test message. That way you'd be enabled to test it yourself. Thanks.

**Comment by calccrypto** [comment]
You can use the [Alicepub key](https://github.com/calccrypto/OpenPGP/blob/master/tests/testvectors/gpg/Alicepub):

```
-----BEGIN PGP PUBLIC KEY BLOCK-----
Version: GnuPG v1

mQENBFOm0SgBCAC8BH6U1HHzzL1SXWpvjhf3sfAFJ8ciw5E854f70AkOOvi+fllB
D2OzmDqVB7dhBFwRUQ5i9ajPvNwYCXakwiVze44G2FMfOMbqqZaVTVUhpnYyMfB8
K0NgXQUqvfOdbGaKyUvIn1QwUtBQUwxwxIpJqXCGfAAXj5B23Q4VHSVGMnZ7KSbp
uqIsbQwhPx9F3nSZE5bX6NEFCM9nkTlBCrMRsSed08DTf6zKVNUjzRSj30iOuPWS
xaGbz+3mfIFwgVxYit850YgZfaQEkqrFsYPDA/bvI7C15I/3Oy2AavsPtPFroydp
JJ06fKDvC5s9V4Utyal5ttVvPcFw4o3LLlNtABEBAAG0JGFsaWNlICh0ZXN0IGtl
eSkgPGFsaWNlQGV4YW1wbGUuY29tPokBOAQTAQIAIgUCU6bRKAIbAwYLCQgHAwIG
FQgCCQoLBBYCAwECHgECF4AACgkQ1dfaccNUlg4EXgf/aIoYolj4Zs9Q8ck43BWx
EpjaC/vWgCQfUlRa9QI3IoWM37V52iLmba423/moF/eXGS6VtwdLq0k4GsuDfxIW
1Ojjwt4vtVR6UVtSNoI7y0s7yhpoRV+phMTcIbGlryMIrqWAwK4so/XbNDvqpVlS
RwLQnkDRkjMU7w8VZGrOyRucbZy6nZuH+nhialIq4VIPCu02HfAPgZGp7LH7EnMu
n25eHEvs45fk3Pus1BkYiCwt+nW5i1RYfwzWEZW9zkG2kDKadGxuN7fi75sGIGvy
gP+T7AuJGSl5BJKplxrKqefhQVhcpBgA3UYrb4I1wPHgtpGlBU2o+QKV9ZSeIvte
XLkBDQRTptEoAQgA2YqsTj9JniJkrr1x6g59io1GkP9z0JElzRl4kvG7WUkrhSPc
XkoLngcCur9lpxET2Wp7ou43zcKuiwsDxnsWwSvWfmg15N4BzYS6ulP7PSIpQlLb
srqFTR/iX0c7asgUE5Jpe8YEnThl2aAPkJlx47GQN1jhGxOkZhz3kIC+rG2d25ET
36eI0vw4oHO40nF9DihyHzfcD3tuuaOJ+AUPrDh7o97a8yIQmVU031GImC1DHQ9t
k9qkixCuejN1cfi7zqWclnd4nu3C/PJXLz0qzprhK0gXqgjZVBpCPQ5g/WV/Myw/
5H7vJC5WcV0lQilxtjgaHmpSu65XTaAHf4OlNQARAQABiQEfBBgBAgAJBQJTptEo
AhsMAAoJENXX2nHDVJYOmusH/0VDpB6353RsZzCj+eoV9mpew8gPo7jdwMGFVW3r
7ZfwCCE+9hMqQAPU4ewTtpy9SrzynZCG02vycaBhLJwcP1dKtvae1y8B8zh7zo9F
eLTUewHuyFRpyM5/fj1Dou89AOvDRaiJPaO3RQOmjGG9+D5hDS03CHBXOg/P0gYv
lc1myZNfRtU5+ezMEWA+tqyjyjj3W6nyobtpVtwgpA/od47/UcdGqSkzkmr+zqqH
amPMgSaahcvqPw2VFt4fi00ShN9EguwiV2vJes6VvDq1qE5Ap/zWBn/B7xIc70jD
hHtoB2/2gM/blPn5EPrIht6Kh9njBFYVk+OrV96NpJl08lM=
=xJuO
-----END PGP PUBLIC KEY BLOCK-----
```

**Comment by kaie** [comment]
[encrypted-for-tests_testvectors_gpg_Alicepub.txt](https://github.com/calccrypto/OpenPGP/files/2914078/encrypted-for-tests_testvectors_gpg_Alicepub.txt)

$ ./cli/OpenPGP decrypt-pka tests/testvectors/gpg/Alicepri test encrypted-for-tests_testvectors_gpg_Alicepub.txt 
terminate called after throwing an instance of 'std::runtime_error'
  what():  Error: Data contains message section. Use CleartextSignature to parse this data.
Aborted (core dumped)

Using this key results in a different error.

**Comment by calccrypto** [comment]
I think I fixed it with 272e0796ec7d622960682b85f767fa6fbaa32e45. The main issues were:

- The file you provided has `CRLF` line endings, which I didn't handle before
- There were some usage errors with Compressed Data Packets
- There were some logic errors in OpenPGP::Message

Please let me know if you are still having issues

**Comment by kaie** [comment]
Thanks. I confirm the issue is fixed when using the message encrypted for the Alicepub key.

However, it still fails to process the message that I had encrypted with the key I had generated.
terminate called after throwing an instance of 'std::runtime_error'
  what():  Error: Data does not form a meaningful PGP Key

If you're interested to analyze further, feel free to generate a key for yourself with this command, and send me your public key:
./cli/OpenPGP generate-keypair --phash SHA256 --pkeysize 3072 --psig SHA256 --shash SHA256 --skeysize 3072 --ssig SHA256 -e idonttellyou@kuix.de -u "Test Mail" -o testmail-0227 -p passphrase

**Comment by calccrypto** [comment]
Apparently the error reading the key was caused by using the wrong formula to get a 2 octet length.

**Comment by calccrypto** [comment]
@kaie Am I able to close this issue?

**Comment by kaie** [comment]
Jason, I confirm you've fixed the issue, I'm able to decrypt my test message, thanks a lot!
