### ISSUE TITLE
Error generating keys

### ISSUE THREAD

**Issue by azurlake** [calccrypto/OpenPGP#45]
Hello,

I freshly built your library and I'm doing some tests. When incorporated to my project, I do the following:

    void generateKeypair(std::string user, std::string password) {
    OpenPGP::KeyGen::Config config;
    config.passphrase = password;
    config.bits       = 2048;
    config.sym        = OpenPGP::Sym::ID::TRIPLEDES;
    config.hash       = OpenPGP::Hash::ID::SHA1;
    config.pka        = OpenPGP::PKA::ID::RSA_ENCRYPT_OR_SIGN;

    OpenPGP::KeyGen::Config::UserID uid;
    uid.user          = user;
    uid.comment       = "N/A";
    uid.email         = "N/A";
    uid.sig           = OpenPGP::Hash::ID::SHA1;
    config.uids.push_back(uid);

    OpenPGP::KeyGen::Config::SubkeyGen subkey;
    subkey.pka        = OpenPGP::PKA::ID::RSA_ENCRYPT_OR_SIGN;
    subkey.bits       = 2048;
    subkey.sym        = OpenPGP::Sym::ID::TRIPLEDES;
    subkey.hash       = OpenPGP::Hash::ID::SHA1;
    subkey.sig        = OpenPGP::Hash::ID::SHA1;
    config.subkeys.push_back(subkey);

    const OpenPGP::SecretKey pri = OpenPGP::KeyGen::generate_key(config); //FAILS <--------
    if (!pri.meaningful()) {
        throw ERROR_CANNOT_CREATE_KEYPAIR;
    }

    (...)

The generate_key(config) function crashes with a "map::at" exception. Haven't dug any further today, I thought it might be something I was doing bad.

Additionally, if I set the sym to AES192 or AES256, I get a "Data must be at least 128 bits long" error, before getting the map::at error.

I can provide more details

**Comment by azurlake** [comment]
Ok, probably related issue: whenever I provide a passphrase, even in the CLI tool, it crashes. Using your CLI tool the error is "key size does not fit defined sizes". It only works for a blank passphrase. The same happens using the OpenPGP.h in my project, but the error is different (map::at).

Cheers and good job

**Comment by calccrypto** [comment]
76f4be051c4a304239fcfce045c9fdd2c057bb87 fixes the `map::at` issue. I will look at the sym issue later.

**Comment by calccrypto** [comment]
Give d6a91beb45a014fc8bb55fa24615f560f4f74fda a try. I don't know how those errors managed to not cause problems earlier.

**Comment by azurlake** [comment]
Thanks, I will check as soon as I get my hands on the computer.

Cheers

**Comment by calccrypto** [comment]
@azurlake Did that commit fix the issue?
