### ISSUE TITLE
Error undefined reference to unhexlify

### ISSUE THREAD

**Issue by pvthuyet** [calccrypto/OpenPGP#47]
Hello,
I got an error when using the library.
Here my environment:
- Ubuntu 18.04
- cmake version 3.10.2
- g++ (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0

cpp test file:
```
#include <iostream>
#include "OpenPGP.h"
int main()
{
  std::cout << "Hello, \n";
  return 1;
}
```
Then build the test.cpp : 
 `g++ -Wall -g -std=c++11 test.cpp`

Finally, i got the error:

> /tmp/cccmQHCv.o: In function `__static_initialization_and_destruction_0(int, int)':
> /usr/local/include/Encryptions/Camellia_Const.h:33: undefined reference to `unhexlify(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
> /usr/local/include/Encryptions/Camellia_Const.h:33: undefined reference to `unhexlify(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
> /usr/local/include/Encryptions/Camellia_Const.h:33: undefined reference to `unhexlify(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
> /usr/local/include/Encryptions/Camellia_Const.h:33: undefined reference to `unhexlify(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
> /usr/local/include/Encryptions/Camellia_Const.h:33: undefined reference to `unhexlify(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
> /tmp/cccmQHCv.o:/usr/local/include/Encryptions/Camellia_Const.h:33: more undefined references to `unhexlify(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)' follow
> collect2: error: ld returned 1 exit status

Any help?

**Comment by calccrypto** [comment]
Hi. You have to link against the library. Assuming your build is in `<OpenPGP>/build`, you have to compile with `g++ -Wall -g -std=c++11 test.cpp -L<OpenPGP>/build -lOpenPGP`.

**Comment by pvthuyet** [comment]
Thank you @calccrypto ,
You save my life :)
