### ISSUE TITLE
Error in CleartextSignature class

### ISSUE THREAD

**Issue by GeorgeKalovyrnas** [calccrypto/OpenPGP#49]
Hi,
Am I doing something wrong or there is indeed an error in CleartextSignature class?
The definition of write() member function of this class doesn't match its implementation.

Regards

**Comment by GeorgeKalovyrnas** [comment]
It seems that many function member prototypes are different than their implementations.
A wrong commit maybe?

**Comment by calccrypto** [comment]
What do you mean? These two are the same. I simply provided default values for the arguments in the declaration.

```cpp
std::string write(Status * status = nullptr, const bool check_mpi = false) const;
std::string CleartextSignature::write(Status * status, const bool check_mpi) const {
```

Which other declarations don't match their definitions?

**Comment by GeorgeKalovyrnas** [comment]
You are right!
There was a mix-up in my repository.
Excuse me for the inconvenience.
