### ISSUE TITLE
Can create pgp sign/verify between two standalone C++ windows app?

### ISSUE THREAD

**Issue by bochen2027** [calccrypto/OpenPGP#50]
Hi, I have two windows C++ applications that pass a string of values back and forth, how can I use your stuff to create a pgp signed version of this so that the communication has another layer of protection? Basically I want the entire pgp password/keys etc to be baked into the two different small applications at compile time, and the end-user it will be completely transparent to them. The two programs communicate back and forth a series of numbers but instead of plaintext it will be PGP encrypted. Is it possible to bake this into the programs internally ?

https://github.com/veracrypt/VeraCrypt/issues/614

**Comment by calccrypto** [comment]
Something along the lines of this should work:

On the sender side:

    OpenPGP::SecretKey sender;
    OpenPGP::PublicKey receiver;
    OpenPGP::Encrypt::Args encrypt_args;
    encrypt_args.data = MESSAGE;
    encrypt_args.signer = std::make_shared <OpenPGP::SecretKey> (sender);
    encrypt_args.passphrase = sender_passphrase;
    const OpenPGP::Message encrypted = OpenPGP::Encrypt::pka(encrypt_args, reciever);
    const std::string encrypted_str = encrypted.write();

On receiver side

    const std::string encrypted_str;
    OpenPGP::Message encrypted(encrypted_str);
    OpenPGP::PublicKey sender;
    OpenPGP::SecretKey receiver;
    const OpenPGP::Message decrypted = OpenPGP::Decrypt::pka(receiver, receiver_passphrase, message);
    OpenPGP::Verify::binary(sender, decrypted);

    // construct message
    std::string message = "";
    for(OpenPGP::Packet::Tag::Ptr const & p : decrypted.get_packets()) {
        if (p -> get_tag() == OpenPGP::Packet::LITERAL_DATA) {
            message += std::dynamic_pointer_cast <OpenPGP::Packet::Tag11> (p) -> out(false);
        }
    }
